/**
 * Phone number configuration
 * Centralized country codes, formats, and validation patterns
 */

import type { CountryCode } from '@/lib/types/phoneInput';

export const COUNTRY_CODES: CountryCode[] = [
  {
    code: '+1',
    country: 'United States',
    abbreviation: 'US',
    emoji: '🇺🇸',
    pattern: /^[2-9]\d{2}[2-9]\d{6}$/,
    format: '(XXX) XXX-XXXX',
    minLength: 10,
    maxLength: 10,
  },
  {
    code: '+1',
    country: 'Canada',
    abbreviation: 'CA',
    emoji: '🇨🇦',
    pattern: /^[2-9]\d{2}[2-9]\d{6}$/,
    format: '(XXX) XXX-XXXX',
    minLength: 10,
    maxLength: 10,
  },
  {
    code: '+44',
    country: 'United Kingdom',
    abbreviation: 'GB',
    emoji: '🇬🇧',
    pattern: /^\d{10}$/,
    format: 'XXXX XXX XXXX',
    minLength: 10,
    maxLength: 10,
  },
  {
    code: '+33',
    country: 'France',
    abbreviation: 'FR',
    emoji: '🇫🇷',
    pattern: /^[1-9]\d{8}$/,
    format: 'X XX XX XX XX',
    minLength: 9,
    maxLength: 9,
  },
  {
    code: '+49',
    country: 'Germany',
    abbreviation: 'DE',
    emoji: '🇩🇪',
    pattern: /^[1-9]\d{8,10}$/,
    format: 'XXX XXXXXXXX',
    minLength: 9,
    maxLength: 11,
  },
  {
    code: '+39',
    country: 'Italy',
    abbreviation: 'IT',
    emoji: '🇮🇹',
    pattern: /^[0-9]{9,10}$/,
    format: 'XXX XXX XXXX',
    minLength: 9,
    maxLength: 10,
  },
  {
    code: '+34',
    country: 'Spain',
    abbreviation: 'ES',
    emoji: '🇪🇸',
    pattern: /^[0-9]{9}$/,
    format: 'XXX XX XX XX',
    minLength: 9,
    maxLength: 9,
  },
  {
    code: '+31',
    country: 'Netherlands',
    abbreviation: 'NL',
    emoji: '🇳🇱',
    pattern: /^[1-9]\d{8}$/,
    format: 'XX XXXX XXXX',
    minLength: 9,
    maxLength: 9,
  },
  {
    code: '+46',
    country: 'Sweden',
    abbreviation: 'SE',
    emoji: '🇸🇪',
    pattern: /^[0-9]{7,9}$/,
    format: 'XXX XXX XXXX',
    minLength: 7,
    maxLength: 9,
  },
  {
    code: '+47',
    country: 'Norway',
    abbreviation: 'NO',
    emoji: '🇳🇴',
    pattern: /^[0-9]{8}$/,
    format: 'XXXX XXXX',
    minLength: 8,
    maxLength: 8,
  },
  {
    code: '+45',
    country: 'Denmark',
    abbreviation: 'DK',
    emoji: '🇩🇰',
    pattern: /^[0-9]{8}$/,
    format: 'XXXX XXXX',
    minLength: 8,
    maxLength: 8,
  },
  {
    code: '+358',
    country: 'Finland',
    abbreviation: 'FI',
    emoji: '🇫🇮',
    pattern: /^[0-9]{9}$/,
    format: 'XXX XXX XXXX',
    minLength: 9,
    maxLength: 9,
  },
  {
    code: '+43',
    country: 'Austria',
    abbreviation: 'AT',
    emoji: '🇦🇹',
    pattern: /^[1-9]\d{8,9}$/,
    format: 'XXX XXXXXXXX',
    minLength: 9,
    maxLength: 10,
  },
  {
    code: '+41',
    country: 'Switzerland',
    abbreviation: 'CH',
    emoji: '🇨🇭',
    pattern: /^[1-9]\d{8}$/,
    format: 'XX XXX XXXX',
    minLength: 9,
    maxLength: 9,
  },
  {
    code: '+32',
    country: 'Belgium',
    abbreviation: 'BE',
    emoji: '🇧🇪',
    pattern: /^[0-9]{8,9}$/,
    format: 'XXX XX XX XX',
    minLength: 8,
    maxLength: 9,
  },
  {
    code: '+48',
    country: 'Poland',
    abbreviation: 'PL',
    emoji: '🇵🇱',
    pattern: /^[0-9]{9}$/,
    format: 'XXX XXX XXXX',
    minLength: 9,
    maxLength: 9,
  },
  {
    code: '+420',
    country: 'Czech Republic',
    abbreviation: 'CZ',
    emoji: '🇨🇿',
    pattern: /^[0-9]{9}$/,
    format: 'XXX XXX XXXX',
    minLength: 9,
    maxLength: 9,
  },
  {
    code: '+36',
    country: 'Hungary',
    abbreviation: 'HU',
    emoji: '🇭🇺',
    pattern: /^[0-9]{9}$/,
    format: 'XXX XXX XXXX',
    minLength: 9,
    maxLength: 9,
  },
  {
    code: '+40',
    country: 'Romania',
    abbreviation: 'RO',
    emoji: '🇷🇴',
    pattern: /^[0-9]{9}$/,
    format: 'XXX XXX XXXX',
    minLength: 9,
    maxLength: 9,
  },
  {
    code: '+90',
    country: 'Turkey',
    abbreviation: 'TR',
    emoji: '🇹🇷',
    pattern: /^[0-9]{10}$/,
    format: 'XXX XXX XXXX',
    minLength: 10,
    maxLength: 10,
  },
  {
    code: '+353',
    country: 'Ireland',
    abbreviation: 'IE',
    emoji: '🇮🇪',
    pattern: /^[0-9]{9}$/,
    format: 'XXX XXX XXXX',
    minLength: 9,
    maxLength: 9,
  },
  {
    code: '+30',
    country: 'Greece',
    abbreviation: 'GR',
    emoji: '🇬🇷',
    pattern: /^[0-9]{9}$/,
    format: 'XXXX XXX XXXX',
    minLength: 9,
    maxLength: 9,
  },
  {
    code: '+385',
    country: 'Croatia',
    abbreviation: 'HR',
    emoji: '🇭🇷',
    pattern: /^[0-9]{8,9}$/,
    format: 'XXX XXX XXXX',
    minLength: 8,
    maxLength: 9,
  },
  {
    code: '+372',
    country: 'Estonia',
    abbreviation: 'EE',
    emoji: '🇪🇪',
    pattern: /^[0-9]{7,8}$/,
    format: 'XXX XXXX',
    minLength: 7,
    maxLength: 8,
  },
  {
    code: '+371',
    country: 'Latvia',
    abbreviation: 'LV',
    emoji: '🇱🇻',
    pattern: /^[0-9]{8}$/,
    format: 'XXXX XXXX',
    minLength: 8,
    maxLength: 8,
  },
  {
    code: '+370',
    country: 'Lithuania',
    abbreviation: 'LT',
    emoji: '🇱🇹',
    pattern: /^[0-9]{8}$/,
    format: 'XXXX XXXX',
    minLength: 8,
    maxLength: 8,
  },
  {
    code: '+359',
    country: 'Bulgaria',
    abbreviation: 'BG',
    emoji: '🇧🇬',
    pattern: /^[0-9]{8,9}$/,
    format: 'XXX XXX XXX',
    minLength: 8,
    maxLength: 9,
  },
  {
    code: '+386',
    country: 'Slovenia',
    abbreviation: 'SI',
    emoji: '🇸🇮',
    pattern: /^[0-9]{8}$/,
    format: 'XXXX XXXX',
    minLength: 8,
    maxLength: 8,
  },
  {
    code: '+389',
    country: 'Macedonia',
    abbreviation: 'MK',
    emoji: '🇲🇰',
    pattern: /^[0-9]{8}$/,
    format: 'XXXX XXXX',
    minLength: 8,
    maxLength: 8,
  },
  {
    code: '+387',
    country: 'Bosnia',
    abbreviation: 'BA',
    emoji: '🇧🇦',
    pattern: /^[0-9]{8}$/,
    format: 'XXXX XXXX',
    minLength: 8,
    maxLength: 8,
  },
  {
    code: '+381',
    country: 'Serbia',
    abbreviation: 'RS',
    emoji: '🇷🇸',
    pattern: /^[0-9]{8,9}$/,
    format: 'XXX XXXX XXX',
    minLength: 8,
    maxLength: 9,
  },
  {
    code: '+355',
    country: 'Albania',
    abbreviation: 'AL',
    emoji: '🇦🇱',
    pattern: /^[0-9]{8}$/,
    format: 'XXXX XXXX',
    minLength: 8,
    maxLength: 8,
  },
  {
    code: '+7',
    country: 'Russia',
    abbreviation: 'RU',
    emoji: '🇷🇺',
    pattern: /^[0-9]{10}$/,
    format: 'XXX XXX XX XX',
    minLength: 10,
    maxLength: 10,
  },
  {
    code: '+380',
    country: 'Ukraine',
    abbreviation: 'UA',
    emoji: '🇺🇦',
    pattern: /^[0-9]{9}$/,
    format: 'XXX XXX XXXX',
    minLength: 9,
    maxLength: 9,
  },
  {
    code: '+375',
    country: 'Belarus',
    abbreviation: 'BY',
    emoji: '🇧🇾',
    pattern: /^[0-9]{9}$/,
    format: 'XXX XXX XXXX',
    minLength: 9,
    maxLength: 9,
  },
  {
    code: '+60',
    country: 'Malaysia',
    abbreviation: 'MY',
    emoji: '🇲🇾',
    pattern: /^[0-9]{9,10}$/,
    format: 'XXX XXXX XXXX',
    minLength: 9,
    maxLength: 10,
  },
  {
    code: '+65',
    country: 'Singapore',
    abbreviation: 'SG',
    emoji: '🇸🇬',
    pattern: /^[0-9]{8}$/,
    format: 'XXXX XXXX',
    minLength: 8,
    maxLength: 8,
  },
  {
    code: '+81',
    country: 'Japan',
    abbreviation: 'JP',
    emoji: '🇯🇵',
    pattern: /^[0-9]{10}$/,
    format: 'XXX XXXX XXXX',
    minLength: 10,
    maxLength: 10,
  },
  {
    code: '+86',
    country: 'China',
    abbreviation: 'CN',
    emoji: '🇨🇳',
    pattern: /^[0-9]{11}$/,
    format: 'XXXX XXX XXXX',
    minLength: 11,
    maxLength: 11,
  },
  {
    code: '+91',
    country: 'India',
    abbreviation: 'IN',
    emoji: '🇮🇳',
    pattern: /^[6-9]\d{9}$/,
    format: 'XXXXX XXXXX',
    minLength: 10,
    maxLength: 10,
  },
  {
    code: '+55',
    country: 'Brazil',
    abbreviation: 'BR',
    emoji: '🇧🇷',
    pattern: /^[0-9]{10,11}$/,
    format: 'XX XXXXX XXXX',
    minLength: 10,
    maxLength: 11,
  },
  {
    code: '+27',
    country: 'South Africa',
    abbreviation: 'ZA',
    emoji: '🇿🇦',
    pattern: /^[0-9]{9}$/,
    format: 'XXX XXX XXXX',
    minLength: 9,
    maxLength: 9,
  },
  {
    code: '+61',
    country: 'Australia',
    abbreviation: 'AU',
    emoji: '🇦🇺',
    pattern: /^[0-9]{9}$/,
    format: 'XXXX XXX XXX',
    minLength: 9,
    maxLength: 9,
  },
  {
    code: '+64',
    country: 'New Zealand',
    abbreviation: 'NZ',
    emoji: '🇳🇿',
    pattern: /^[0-9]{8,9}$/,
    format: 'XXXX XXXX',
    minLength: 8,
    maxLength: 9,
  },
  {
    code: '+82',
    country: 'South Korea',
    abbreviation: 'KR',
    emoji: '🇰🇷',
    pattern: /^[0-9]{9,10}$/,
    format: 'XXXX XXXX',
    minLength: 9,
    maxLength: 10,
  },
  {
    code: '+66',
    country: 'Thailand',
    abbreviation: 'TH',
    emoji: '🇹🇭',
    pattern: /^[0-9]{9}$/,
    format: 'XXXX XXXXX',
    minLength: 9,
    maxLength: 9,
  },
  {
    code: '+84',
    country: 'Vietnam',
    abbreviation: 'VN',
    emoji: '🇻🇳',
    pattern: /^[0-9]{9,10}$/,
    format: 'XXXX XXXXXX',
    minLength: 9,
    maxLength: 10,
  },
  {
    code: '+62',
    country: 'Indonesia',
    abbreviation: 'ID',
    emoji: '🇮🇩',
    pattern: /^[0-9]{9,11}$/,
    format: 'XXXX XXXX XXXX',
    minLength: 9,
    maxLength: 11,
  },
  {
    code: '+63',
    country: 'Philippines',
    abbreviation: 'PH',
    emoji: '🇵🇭',
    pattern: /^[0-9]{10}$/,
    format: 'XXX XXX XXXX',
    minLength: 10,
    maxLength: 10,
  },
  {
    code: '+92',
    country: 'Pakistan',
    abbreviation: 'PK',
    emoji: '🇵🇰',
    pattern: /^[0-9]{10}$/,
    format: 'XXXX XXXXXX',
    minLength: 10,
    maxLength: 10,
  },
  {
    code: '+20',
    country: 'Egypt',
    abbreviation: 'EG',
    emoji: '🇪🇬',
    pattern: /^[0-9]{9,10}$/,
    format: 'XXXX XXXXXX',
    minLength: 9,
    maxLength: 10,
  },
  {
    code: '+212',
    country: 'Morocco',
    abbreviation: 'MA',
    emoji: '🇲🇦',
    pattern: /^[0-9]{9}$/,
    format: 'XXX XXX XXXX',
    minLength: 9,
    maxLength: 9,
  },
  {
    code: '+234',
    country: 'Nigeria',
    abbreviation: 'NG',
    emoji: '🇳🇬',
    pattern: /^[0-9]{10}$/,
    format: 'XXXX XXXXXX',
    minLength: 10,
    maxLength: 10,
  },
  {
    code: '+56',
    country: 'Chile',
    abbreviation: 'CL',
    emoji: '🇨🇱',
    pattern: /^[0-9]{8,9}$/,
    format: 'XXXX XXXX',
    minLength: 8,
    maxLength: 9,
  },
  {
    code: '+57',
    country: 'Colombia',
    abbreviation: 'CO',
    emoji: '🇨🇴',
    pattern: /^[0-9]{10}$/,
    format: 'XXXX XXXXXX',
    minLength: 10,
    maxLength: 10,
  },
  {
    code: '+52',
    country: 'Mexico',
    abbreviation: 'MX',
    emoji: '🇲🇽',
    pattern: /^[0-9]{10}$/,
    format: 'XXXXX XXXXX',
    minLength: 10,
    maxLength: 10,
  },
];

/**
 * Get filtered unique country codes (removes duplicates by code-abbreviation)
 */
export const getUniqueCountryCodes = (): typeof COUNTRY_CODES =>
  Array.from(
    new Map(
      COUNTRY_CODES.map((item) => [`${item.code}-${item.abbreviation}`, item]),
    ).values(),
  );

/**
 * Default country code for Philippines
 */
export const DEFAULT_COUNTRY_CODE = COUNTRY_CODES.find(
  (c) => c.code === '+63' && c.abbreviation === 'PH',
)!;
