/**
 * Event Domain Types
 *
 * An event is the one thing in this app with a DATE. Shops, offerings and
 * deals are ambient; an event starts and stops, which is why it carries a span
 * and an optional daily window rather than a single timestamp.
 *
 * Two authors share the table: `business_id === null` is a platform event an
 * admin wrote, anything else is a shop's proposal. `status` is decided by a DB
 * trigger, never by a client — see `20260802034107_events.sql`.
 */

/** Runtime mirror of the `events.status` CHECK. */
export type EventStatus = 'draft' | 'pending_review' | 'approved' | 'rejected';

export const EVENT_STATUSES = [
  'draft',
  'pending_review',
  'approved',
  'rejected',
] as const satisfies readonly EventStatus[];

/**
 * Owner-facing status copy. `description` exists because the four words alone
 * do not tell an owner what to do next, and "pending" with no explanation
 * reads as broken.
 */
export const EVENT_STATUS_OPTIONS: ReadonlyArray<{
  value: EventStatus;
  label: string;
  description: string;
}> = [
  {
    value: 'draft',
    label: 'Draft',
    description: 'Only you can see this. Submit it when it is ready.',
  },
  {
    value: 'pending_review',
    label: 'In review',
    description: 'Waiting on the iLokal team. You can still withdraw it.',
  },
  {
    value: 'approved',
    label: 'Published',
    description: 'Live on iLokal. Editing it sends it back for review.',
  },
  {
    value: 'rejected',
    label: 'Not approved',
    description: 'Read the note, make the changes, and submit again.',
  },
];

/** A row as stored. `location` is PostGIS and never round-trips through here. */
export interface Event {
  id: string;
  /** null = a platform event authored by an admin. */
  business_id: string | null;
  /** The one offering this event promotes, if any. */
  product_id: string | null;

  name: string;
  description: string | null;
  address: string;
  /**
   * Read-only projections of the PostGIS `location`, generated by the DB.
   * PostgREST hands back `location` itself as WKB hex, which no form can use.
   * Never written — `location` is the source of truth.
   */
  latitude: number | null;
  longitude: number | null;
  image_url: string | null;

  /** Both carry date AND time. */
  starts_at: string;
  ends_at: string;
  /**
   * With `daily_end_time`: the event opens these hours on each day of the run.
   * Both null = it runs continuously from `starts_at` to `ends_at`.
   * `daily_end_time` earlier than `daily_start_time` closes after midnight.
   */
  daily_start_time: string | null;
  daily_end_time: string | null;

  /** The event's own site. */
  link_url: string | null;
  /** Where to buy a ticket. Deliberately separate from `link_url`. */
  ticket_url: string | null;

  status: EventStatus;
  review_note: string | null;
  reviewed_by: string | null;
  reviewed_at: string | null;
  /** Banner order. Admin-only — the trigger zeroes any owner-supplied value. */
  priority: number;

  created_at: string;
  updated_at: string;
  archived_at: string | null;
}

/** The shop an event belongs to, as embedded on a read. */
export interface EventBusinessRef {
  id: string;
  shop_name: string;
  logo_url: string | null;
}

/** The offering an event promotes, as embedded on a read. */
export interface EventProductRef {
  id: string;
  name: string;
  image_url: string | null;
}

/** What every public surface renders. */
export interface EventWithRefs extends Event {
  business: EventBusinessRef | null;
  product: EventProductRef | null;
  /** Present only on `events_nearby` reads. */
  distance_meters?: number;
}

/** One row of the `events_nearby` RPC. */
export interface NearbyEvent {
  id: string;
  name: string;
  description: string | null;
  address: string;
  // No latitude/longitude here: `events_nearby` does not project them, and a
  // type that claims columns the RPC never returns is worse than no type.
  image_url: string | null;
  starts_at: string;
  ends_at: string;
  daily_start_time: string | null;
  daily_end_time: string | null;
  distance_meters: number;
  business_id: string | null;
  business_name: string | null;
}

export interface EventListMetadata {
  total: number;
  page: number;
  per_page: number;
  total_pages: number;
}

export interface PaginatedEvents {
  events: EventWithRefs[];
  metadata: EventListMetadata;
}

/** Which slice of time a public list is asking for. */
export type EventTimeFilter = 'upcoming' | 'past' | 'all';

export const EVENT_TIME_FILTERS = [
  'upcoming',
  'past',
  'all',
] as const satisfies readonly EventTimeFilter[];

export interface EventFilters {
  page?: number;
  per_page?: number;
  search?: string;
  /** Owner/admin views only — the public list never sees anything but approved. */
  status?: EventStatus | '';
  business_id?: string;
  when?: EventTimeFilter;
}

/** Payload an admin sends when deciding a proposal. */
export type EventDecision = 'approve' | 'reject';
